# -*- coding: utf-8 -*-
"""input_image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n4mOXiDrCxQL0abSwwIbBP5YXaFn_Axj
"""

import torch
from torchvision import transforms
from google.colab.patches import cv2_imshow
import cv2

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/image_cutout/

####이미지 명암, 대조, saturation, hue조정하기
#넘파이 array를 torch형태로 변환하기 

path='이미지 상대경로 및 절대경로'
img=cv2.imread(path)
img=torch.from_numpy(img)
print(img.size())
img=img.permute(2,0,1)
img=transforms.ColorJitter(brightness=0.3,contrast=0.3,saturation=0.4)(img)

img=img.permute(1,2,0)
print(img.size())
img=img.numpy()
cv2_imshow(img)


